### ISSUE TITLE
[WIP] Reduce bundle size by limiting lodash usage

### ISSUE THREAD

**Issue by bravo-kernel** [alt3/sequelize-to-json-schemas#26]
- v0.3.23 measured **[29.2 kB minified/gzipped](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas@0.3.23)**
- v0.3.24  measured **[11.3 kB  minified/gzipped](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas@0.3.24)** (after PR https://github.com/alt3/sequelize-to-json-schemas/pull/28 cherry picking)
- v0.3.25  measured **[11.3 kB  minified/gzipped](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas@0.3.25)** (after PR https://github.com/alt3/sequelize-to-json-schemas/pull/29 separating devDependencies)
- v0.3.27  measured **[10.9 kB  minified/gzipped](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas@0.3.27)** (after replacing lodash.capitalize)
- v0.3.28  measured **[10.7 kB  minified/gzipped](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas@0.3.28)** (after replacing lodash.pick)
- v0.3.29  measured **[5.2 kB  minified/gzipped](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas@0.3.28)** (after completely removing lodash)

### Background information

- [BundlePhobia analysis](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas) for sequelize-to-json-schemas
- [NPM Trends bundle size comparison](https://www.npmtrends.com/@alt3/sequelize-to-json-schemas-vs-sequelize-json-schema-vs-sequelize-to-json-vs-sequelize-to-json-schema) with similar libraries
- [You-Dont-Need-Lodash-Underscore](https://github.com/you-dont-need/You-Dont-Need-Lodash-Underscore)

### TODO

ONLY replace if the vanilla alternative is cross-browser, otherwise stick to lodash.

- [x] capitalize (used 1x, replaced in https://github.com/alt3/sequelize-to-json-schemas/commit/90d9b3cab781ad4c9b4ff0b7f82f4c2339fc57e7)
- [X] pick (use 1x, replaced in f875dae06306e64c9bf7302364fe031bbf9ab4a3)
- [X] assign (used 12x)
- [X] omit (used 1x)
- [X] merge (used 3x, [high impact](https://bundlephobia.com/result?p=@alt3/sequelize-to-json-schemas))

_**Dev-only, no impact:**_

- cloneDeep (used 2x)

**Comment by bravo-kernel** [comment]
Closing as we are now the 2nd smallest library compared to the alternatives. 

https://www.npmtrends.com/@alt3/sequelize-to-json-schemas-vs-sequelize-json-schema-vs-sequelize-to-json-vs-sequelize-to-json-schema
